chave = input('Digite a sua chave: ')

senha = ''

for letra in chave:
    if letra in 'Aa': senha = senha + '&'
    elif letra in 'Bb': senha = senha + '7'
    elif letra in 'Cc': senha = senha + '0'
    elif letra in 'Dd': senha = senha + '4'
    elif letra in 'Ee': senha = senha + '1'
    elif letra in 'Ff': senha = senha + '5'
    elif letra in 'Gg': senha = senha + '-'
    elif letra in 'Hh': senha = senha + '='
    elif letra in 'Ii': senha = senha + '+'
    elif letra in 'Jj': senha = senha + '!'
    elif letra in 'Kk': senha = senha + '$'
    elif letra in 'Ll': senha = senha + 'h'
    elif letra in 'Mm': senha = senha + 'L'
    elif letra in 'Nn': senha = senha + '>'
    elif letra in 'Oo': senha = senha + ':'
    elif letra in 'Pp': senha = senha + '^'
    elif letra in 'Qq': senha = senha + '3'
    elif letra in 'Rr': senha = senha + '%'
    elif letra in 'Ss': senha = senha + 'y'
    elif letra in 'Tt': senha = senha + '9'
    elif letra in 'Uu': senha = senha + 'q'
    elif letra in 'Vv': senha = senha + '.'
    elif letra in 'Ww': senha = senha + ';'
    elif letra in 'Xx': senha = senha + '/'
    elif letra in 'Yy': senha = senha + '?'
    elif letra in 'Zz': senha = senha + '_'
    elif letra in '1': senha = senha + ']'
    elif letra in '2': senha = senha + '{'
    elif letra in '3': senha = senha + 'x'
    elif letra in '3': senha = senha + '('
    elif letra in '4': senha = senha + '*'
    elif letra in '5': senha = senha + '6'
    elif letra in '6': senha = senha + 'p'
    elif letra in '7': senha = senha + 'P'
    elif letra in '8': senha = senha + 'K'
    elif letra in '9': senha = senha + 'V'
    elif letra in '0': senha = senha + 'Ç'
    else: senha = senha + letra

print(senha)